/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.DBManager;
import db.Record;
import javax.swing.JOptionPane;

/**
 *
 * @author jwolf
 */
public class AddAdvertisement extends javax.swing.JFrame {

    /**
     * Creates new form AddAdvertisement
     */
    DBManager DB;
    String userID;
    UserView parent;

    public AddAdvertisement(UserView parent, DBManager DB, String userID) {
        setTitle("Add Advertisement");
        this.parent = parent;
        this.DB = DB;
        this.userID = userID;
        initComponents();
        populateCategories();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_Title_Label = new javax.swing.JLabel();
        Add_Title_Field = new javax.swing.JTextField();
        Add_Details_Label = new javax.swing.JLabel();
        Add_Details_Container = new javax.swing.JScrollPane();
        Add_Details_Field = new javax.swing.JTextArea();
        Add_Category_Label = new javax.swing.JLabel();
        Add_Category_ComboBox = new javax.swing.JComboBox<>();
        Add_Price_Label = new javax.swing.JLabel();
        Add_Price_Field = new javax.swing.JTextField();
        Add_Add_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Advertisement");

        Add_Title_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Add_Title_Label.setLabelFor(Add_Title_Field);
        Add_Title_Label.setText("Title:");

        Add_Title_Field.setToolTipText("Enter a descriptive title for the item.");

        Add_Details_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Add_Details_Label.setLabelFor(Add_Details_Field);
        Add_Details_Label.setText("Details:");

        Add_Details_Container.setToolTipText("");

        Add_Details_Field.setColumns(20);
        Add_Details_Field.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        Add_Details_Field.setLineWrap(true);
        Add_Details_Field.setRows(5);
        Add_Details_Field.setTabSize(1);
        Add_Details_Field.setToolTipText("Enter details about the item.");
        Add_Details_Field.setWrapStyleWord(true);
        Add_Details_Container.setViewportView(Add_Details_Field);

        Add_Category_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Add_Category_Label.setLabelFor(Add_Category_ComboBox);
        Add_Category_Label.setText("Category:");
        Add_Category_Label.setToolTipText("");

        Add_Category_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        Add_Price_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Add_Price_Label.setLabelFor(Add_Price_Field);
        Add_Price_Label.setText("Price:");

        Add_Price_Field.setToolTipText("Enter the item's price.");

        Add_Add_Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Add_Add_Button.setText("Add Advertisement");
        Add_Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Add_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Add_Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Add_Category_Label)
                            .addComponent(Add_Details_Label)
                            .addComponent(Add_Price_Label)
                            .addComponent(Add_Title_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Add_Price_Field)
                            .addComponent(Add_Title_Field)
                            .addComponent(Add_Details_Container)
                            .addComponent(Add_Category_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_Title_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Title_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Add_Details_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Details_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_Category_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Category_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_Price_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_Price_Label))
                .addGap(18, 18, 18)
                .addComponent(Add_Add_Button)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add_Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Add_ButtonActionPerformed
        String title = this.Add_Title_Field.getText();
        String details = this.Add_Details_Field.getText();
        Record category = (Record) this.Add_Category_ComboBox.getSelectedItem();
        String price = this.Add_Price_Field.getText();

        if (title.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Title field is empty", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (details.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Details field is empty", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (category.getID().equals("Choose")) {
            JOptionPane.showMessageDialog(this, "No category selected", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (price.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Price field is empty", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean result = DB.addAdvertisement(title, details, price, category.getID(), userID);
        if (result) {
            JOptionPane.showMessageDialog(this,
                    "The new advertisement was added",
                    "Confirmation",
                    JOptionPane.INFORMATION_MESSAGE);
            parent.populateUserAdsTable(userID);
            this.setVisible(false);
        }
    }//GEN-LAST:event_Add_Add_ButtonActionPerformed

    private void populateCategories() {
        this.Add_Category_ComboBox.removeAllItems();
        this.Add_Category_ComboBox.addItem(new Record("Choose", "<Choose a category>"));
        for (Record category : DB.getCategories()) {
            this.Add_Category_ComboBox.addItem(category);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Add_Button;
    private javax.swing.JComboBox<Record> Add_Category_ComboBox;
    private javax.swing.JLabel Add_Category_Label;
    private javax.swing.JScrollPane Add_Details_Container;
    private javax.swing.JTextArea Add_Details_Field;
    private javax.swing.JLabel Add_Details_Label;
    private javax.swing.JTextField Add_Price_Field;
    private javax.swing.JLabel Add_Price_Label;
    private javax.swing.JTextField Add_Title_Field;
    private javax.swing.JLabel Add_Title_Label;
    // End of variables declaration//GEN-END:variables
}
