/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.DBManager;
import javax.swing.JOptionPane;

/**
 *
 * @author jwolf
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    DBManager DB;

    public LoginScreen(DBManager DB) {
        this.setTitle("Login");
        this.DB=DB;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_AdManager_Title = new javax.swing.JLabel();
        Login_Username_Label = new javax.swing.JLabel();
        Login_Username_Field = new javax.swing.JTextField();
        Login_UserType_Label = new javax.swing.JLabel();
        Login_UserType_ComboBox = new javax.swing.JComboBox<>();
        Login_Login_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        Login_AdManager_Title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Login_AdManager_Title.setText("SimWolf Ad Manager");

        Login_Username_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Login_Username_Label.setLabelFor(Login_Username_Field);
        Login_Username_Label.setText("Username:");
        Login_Username_Label.setAutoscrolls(true);

        Login_UserType_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Login_UserType_Label.setLabelFor(Login_UserType_ComboBox);
        Login_UserType_Label.setText("Type:");

        Login_UserType_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Login_UserType_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Moderator" }));

        Login_Login_Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Login_Login_Button.setText("Login");
        Login_Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_Login_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Login_Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Login_Username_Label)
                                .addComponent(Login_UserType_Label))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Login_Username_Field)
                                .addComponent(Login_UserType_ComboBox, 0, 163, Short.MAX_VALUE))))
                    .addComponent(Login_AdManager_Title))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Login_AdManager_Title)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_Username_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login_Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_UserType_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login_UserType_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Login_Login_Button)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_Login_ButtonActionPerformed
        String userID=this.Login_Username_Field.getText();
        String userType=(String)Login_UserType_ComboBox.getSelectedItem().toString();
        if(userType == "User"){
            boolean result=DB.checkUser(userID);
            if (!result) {
                JOptionPane.showMessageDialog(this, "Invalid User ID", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
<<<<<<< HEAD
                UserView userView = new UserView(DB, userID);
                userView.setVisible(true);
                this.setVisible(false);
=======
//                UserView userView = new UserView(DB, employeeID);
//                userView.setVisible(true);
//                this.setVisible(false);
>>>>>>> a70d720eb67286fadfd83af74420aa1fa6af0798
            }
        } else {
            boolean result=DB.checkModerator(userID);
            if (!result) {
                JOptionPane.showMessageDialog(this, "Invalid Moderator ID", "Error", JOptionPane.ERROR_MESSAGE);
            } //else {
//                ModeratorView moderatorView = new ModeratorView(DB, userID);
//                moderatorView.setVisible(true);
//                this.setVisible(false);
//            }
        }
    }//GEN-LAST:event_Login_Login_ButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_AdManager_Title;
    private javax.swing.JButton Login_Login_Button;
    private javax.swing.JComboBox<String> Login_UserType_ComboBox;
    private javax.swing.JLabel Login_UserType_Label;
    private javax.swing.JTextField Login_Username_Field;
    private javax.swing.JLabel Login_Username_Label;
    // End of variables declaration//GEN-END:variables
}
