/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.DBManager;
import db.Record;
import db.Advertisement;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jwolf
 */
public class ModeratorView extends javax.swing.JFrame {

    /**
     * Creates new form ModeratorView
     */
    DBManager DB;
    String userID;
    String[] unclaimedAdsColumns
            = new String[]{"Ad ID", "Title", "Description", "Price", "Category", "User", "Date"};
    String[] moderatorAdsColumn
            = new String[]{"Ad ID", "Title", "Description", "Price", "Category", "User", "Status", "Date"};
    LinkedList<Advertisement> adList;
    
    public ModeratorView(DBManager DB, String userID) {
        this.setTitle("Moderator: " + userID);
        this.DB = DB;
        this.userID = userID;
        initComponents();
        this.populateCategories();
        this.populateUnclaimedAdsTable();
        this.populateModeratorAdsTable(userID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Moderator_Tab_Container = new javax.swing.JTabbedPane();
        Moderator_UnclaimedAds_Tab = new javax.swing.JPanel();
        Moderator_Category_Label = new javax.swing.JLabel();
        Moderator_Category_ComboBox = new javax.swing.JComboBox<>();
        Moderator_Period_Label = new javax.swing.JLabel();
        Moderator_Period_ComboBox = new javax.swing.JComboBox<>();
        Moderator_SearchString_Label = new javax.swing.JLabel();
        Moderator_SearchString_Field = new javax.swing.JTextField();
        Moderator_ClaimAd_Button = new javax.swing.JButton();
        Moderator_UnclaimedAdsResults_Container = new javax.swing.JScrollPane();
        Moderator_UnclaimedAdsResults_Table = new javax.swing.JTable();
        Moderator_FilterResults_Label = new javax.swing.JLabel();
        Moderator_MyAds_Tab = new javax.swing.JPanel();
        Moderator_Edit_Button = new javax.swing.JButton();
        Moderator_Delete_Button = new javax.swing.JButton();
        Moderator_MyAdsResults_Container = new javax.swing.JScrollPane();
        Moderator_MyAdsResults_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Moderator_Tab_Container.setToolTipText("");
        Moderator_Tab_Container.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Moderator_Tab_Container.setName("Moderator_Tab_Container"); // NOI18N

        Moderator_UnclaimedAds_Tab.setToolTipText("");
        Moderator_UnclaimedAds_Tab.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Moderator_UnclaimedAds_TabComponentShown(evt);
            }
        });

        Moderator_Category_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Moderator_Category_Label.setLabelFor(Moderator_Category_ComboBox);
        Moderator_Category_Label.setText("Category");

        Moderator_Category_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Moderator_Category_ComboBox.setToolTipText("Select an item category to search.");

        Moderator_Period_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Moderator_Period_Label.setLabelFor(Moderator_Period_ComboBox);
        Moderator_Period_Label.setText("Period");

        Moderator_Period_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Moderator_Period_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "This Month", "Last Month", "Last 3 Months", "Last 6 Months", "Last Year", "Any Date" }));
        Moderator_Period_ComboBox.setToolTipText("Select a timeframe to search within.");

        Moderator_SearchString_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Moderator_SearchString_Label.setLabelFor(Moderator_SearchString_Field);
        Moderator_SearchString_Label.setText("Title, Description");

        Moderator_SearchString_Field.setToolTipText("Enter keyword(s) to search for.");

        Moderator_ClaimAd_Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Moderator_ClaimAd_Button.setText("Claim Ad");
        Moderator_ClaimAd_Button.setToolTipText("Claim the currently highlighted advertisement to moderate.");
        Moderator_ClaimAd_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Moderator_ClaimAd_ButtonActionPerformed(evt);
            }
        });

        Moderator_UnclaimedAdsResults_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Description", "Price", "Category", "User", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Moderator_UnclaimedAdsResults_Table.getTableHeader().setReorderingAllowed(false);
        Moderator_UnclaimedAdsResults_Container.setViewportView(Moderator_UnclaimedAdsResults_Table);

        Moderator_FilterResults_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Moderator_FilterResults_Label.setText("Filter Results By:");

        javax.swing.GroupLayout Moderator_UnclaimedAds_TabLayout = new javax.swing.GroupLayout(Moderator_UnclaimedAds_Tab);
        Moderator_UnclaimedAds_Tab.setLayout(Moderator_UnclaimedAds_TabLayout);
        Moderator_UnclaimedAds_TabLayout.setHorizontalGroup(
            Moderator_UnclaimedAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Moderator_UnclaimedAds_TabLayout.createSequentialGroup()
                .addGroup(Moderator_UnclaimedAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Moderator_UnclaimedAds_TabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Moderator_UnclaimedAdsResults_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Moderator_UnclaimedAds_TabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Moderator_UnclaimedAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Moderator_ClaimAd_Button, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Moderator_UnclaimedAds_TabLayout.createSequentialGroup()
                                .addComponent(Moderator_FilterResults_Label)
                                .addGap(18, 18, 18)
                                .addGroup(Moderator_UnclaimedAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Moderator_UnclaimedAds_TabLayout.createSequentialGroup()
                                        .addGroup(Moderator_UnclaimedAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Moderator_Category_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Moderator_Category_Label))
                                        .addGap(18, 18, 18)
                                        .addGroup(Moderator_UnclaimedAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Moderator_Period_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Moderator_Period_Label))
                                        .addGap(18, 18, 18)
                                        .addComponent(Moderator_SearchString_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Moderator_UnclaimedAds_TabLayout.createSequentialGroup()
                                        .addGap(300, 300, 300)
                                        .addComponent(Moderator_SearchString_Label)))))))
                .addContainerGap())
        );
        Moderator_UnclaimedAds_TabLayout.setVerticalGroup(
            Moderator_UnclaimedAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Moderator_UnclaimedAds_TabLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(Moderator_UnclaimedAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Moderator_Category_Label)
                    .addComponent(Moderator_Period_Label)
                    .addComponent(Moderator_SearchString_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Moderator_UnclaimedAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Moderator_Category_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Moderator_Period_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Moderator_SearchString_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Moderator_FilterResults_Label))
                .addGap(18, 18, 18)
                .addComponent(Moderator_ClaimAd_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Moderator_UnclaimedAdsResults_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        Moderator_Tab_Container.addTab("Unclaimed Advertisements", null, Moderator_UnclaimedAds_Tab, "View advertisements without an assigned moderator.");
        Moderator_UnclaimedAds_Tab.getAccessibleContext().setAccessibleName("");

        Moderator_MyAds_Tab.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                Moderator_MyAds_TabComponentShown(evt);
            }
        });

        Moderator_Edit_Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Moderator_Edit_Button.setText("Edit");
        Moderator_Edit_Button.setToolTipText("Edit the currently highlighted advertisement.");
        Moderator_Edit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Moderator_Edit_ButtonActionPerformed(evt);
            }
        });

        Moderator_Delete_Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Moderator_Delete_Button.setText("Delete");
        Moderator_Delete_Button.setToolTipText("Delete the currently highlighted advertisement.");
        Moderator_Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Moderator_Delete_ButtonActionPerformed(evt);
            }
        });

        Moderator_MyAdsResults_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Description", "Price", "Category", "User", "Status", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Moderator_MyAdsResults_Table.getTableHeader().setReorderingAllowed(false);
        Moderator_MyAdsResults_Container.setViewportView(Moderator_MyAdsResults_Table);

        javax.swing.GroupLayout Moderator_MyAds_TabLayout = new javax.swing.GroupLayout(Moderator_MyAds_Tab);
        Moderator_MyAds_Tab.setLayout(Moderator_MyAds_TabLayout);
        Moderator_MyAds_TabLayout.setHorizontalGroup(
            Moderator_MyAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Moderator_MyAds_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Moderator_MyAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Moderator_MyAdsResults_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addGroup(Moderator_MyAds_TabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Moderator_Edit_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Moderator_Delete_Button)))
                .addContainerGap())
        );
        Moderator_MyAds_TabLayout.setVerticalGroup(
            Moderator_MyAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Moderator_MyAds_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Moderator_MyAds_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Moderator_Delete_Button)
                    .addComponent(Moderator_Edit_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Moderator_MyAdsResults_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Moderator_Tab_Container.addTab("My Advertisements", null, Moderator_MyAds_Tab, "View advertisements assigned to you.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Moderator_Tab_Container)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Moderator_Tab_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Moderator_Tab_Container.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Moderator_UnclaimedAds_TabComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Moderator_UnclaimedAds_TabComponentShown
        populateUnclaimedAdsTable();
    }//GEN-LAST:event_Moderator_UnclaimedAds_TabComponentShown

    private void Moderator_MyAds_TabComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Moderator_MyAds_TabComponentShown
        populateModeratorAdsTable(userID);
    }//GEN-LAST:event_Moderator_MyAds_TabComponentShown

    private void Moderator_ClaimAd_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Moderator_ClaimAd_ButtonActionPerformed
        int row = Moderator_UnclaimedAdsResults_Table.getSelectedRow();
        int adID = (Integer) Moderator_UnclaimedAdsResults_Table.getValueAt(row, 0);
        int reply = JOptionPane.showConfirmDialog(this, "Confirm claim", "Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            if (DB.claimAdvertisement(adID, userID));
            JOptionPane.showMessageDialog(this,
                    "The advertisement has been claimed",
                    "Confirmation",
                    JOptionPane.INFORMATION_MESSAGE);
            populateModeratorAdsTable(userID);
            populateUnclaimedAdsTable();
            return;
        }
        return;

    }//GEN-LAST:event_Moderator_ClaimAd_ButtonActionPerformed

    private void Moderator_Edit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Moderator_Edit_ButtonActionPerformed
        int row = Moderator_MyAdsResults_Table.getSelectedRow();
        int adID = (Integer) Moderator_MyAdsResults_Table.getValueAt(row, 0);
        ModeratorEditAdvertisement editAd = new ModeratorEditAdvertisement(this, DB, adID, userID);
        editAd.setVisible(true);
    }//GEN-LAST:event_Moderator_Edit_ButtonActionPerformed

    private void Moderator_Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Moderator_Delete_ButtonActionPerformed
        int row = Moderator_MyAdsResults_Table.getSelectedRow();
        int adID = (Integer) Moderator_MyAdsResults_Table.getValueAt(row, 0);
        int reply = JOptionPane.showConfirmDialog(this, "Confirm deletion", "Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            if (DB.deleteAdByID(adID));
            JOptionPane.showMessageDialog(this,
                    "The advertisement was deleted",
                    "Confirmation",
                    JOptionPane.INFORMATION_MESSAGE);
            populateModeratorAdsTable(userID);
            return;
        }
        return;
    }//GEN-LAST:event_Moderator_Delete_ButtonActionPerformed

        private void Moderator_SearchString_FieldKeyReleased(java.awt.event.KeyEvent evt) {                                                    
        String category = this.Moderator_Category_ComboBox.getSelectedItem().toString();
        String period = this.Moderator_Period_ComboBox.getSelectedItem().toString();
        String searchText = this.Moderator_SearchString_Field.getText();
        populateModeratorAdsTable(userID);
    }                                                   
        
    private void populateCategories() {
        this.Moderator_Category_ComboBox.removeAllItems();
        this.Moderator_Category_ComboBox.addItem(new Record("All", "All"));
        for (Record category : DB.getCategories()) {
            this.Moderator_Category_ComboBox.addItem(category);
        }
    }

    public void populateUnclaimedAdsTable() {
        adList = new LinkedList();
        //TODO: Update search function for Moderator Search
        Object[][] Moderator_unclaimedAds = DB.getAllUnclaimedAds();
        this.Moderator_UnclaimedAdsResults_Table.setModel(new DefaultTableModel(Moderator_unclaimedAds, unclaimedAdsColumns));
    }

    public void populateModeratorAdsTable(String userID) {
        Object[][] Moderator_myAds = DB.getAllModeratorsAds(userID);
        this.Moderator_MyAdsResults_Table.setModel(new DefaultTableModel(Moderator_myAds, moderatorAdsColumn));
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Record> Moderator_Category_ComboBox;
    private javax.swing.JLabel Moderator_Category_Label;
    private javax.swing.JButton Moderator_ClaimAd_Button;
    private javax.swing.JButton Moderator_Delete_Button;
    private javax.swing.JButton Moderator_Edit_Button;
    private javax.swing.JLabel Moderator_FilterResults_Label;
    private javax.swing.JScrollPane Moderator_MyAdsResults_Container;
    private javax.swing.JTable Moderator_MyAdsResults_Table;
    private javax.swing.JPanel Moderator_MyAds_Tab;
    private javax.swing.JComboBox<String> Moderator_Period_ComboBox;
    private javax.swing.JLabel Moderator_Period_Label;
    private javax.swing.JTextField Moderator_SearchString_Field;
    private javax.swing.JLabel Moderator_SearchString_Label;
    private javax.swing.JTabbedPane Moderator_Tab_Container;
    private javax.swing.JScrollPane Moderator_UnclaimedAdsResults_Container;
    private javax.swing.JTable Moderator_UnclaimedAdsResults_Table;
    private javax.swing.JPanel Moderator_UnclaimedAds_Tab;
    // End of variables declaration//GEN-END:variables
}
