/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.DBManager;
import db.Record;
import db.Advertisement;
import Utilities.Utilities;
import com.mysql.jdbc.StringUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author jwolf
 */
public class UserEditAdvertisement extends javax.swing.JFrame {

    /**
     * Creates new form UserEditAdvertisement
     */
    DBManager DB;
    int adID;
    String userID;
    UserView parent;
    Advertisement advertisement = null;

    public UserEditAdvertisement(UserView parent, DBManager DB, int adID, String userID) {
        setTitle("Edit Ad: " + adID);
        this.parent = parent;
        this.DB = DB;
        this.adID = adID;
        this.userID = userID;
        initComponents();
        populateCategories();
        populateTable(adID);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserEdit_Title_Label = new javax.swing.JLabel();
        UserEdit_Title_Field = new javax.swing.JTextField();
        UserEdit_Details_Label = new javax.swing.JLabel();
        UserEdit_Details_Container = new javax.swing.JScrollPane();
        UserEdit_Details_Field = new javax.swing.JTextArea();
        UserEdit_Category_Label = new javax.swing.JLabel();
        UserEdit_Category_ComboBox = new javax.swing.JComboBox<>();
        UserEdit_Price_Label = new javax.swing.JLabel();
        UserEdit_Price_Field = new javax.swing.JTextField();
        UserEdit_Update_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Advertisement");

        UserEdit_Title_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserEdit_Title_Label.setText("Title:");

        UserEdit_Title_Field.setToolTipText("Enter a descriptive title for the item.");

        UserEdit_Details_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserEdit_Details_Label.setText("Details:");

        UserEdit_Details_Container.setToolTipText("");

        UserEdit_Details_Field.setColumns(20);
        UserEdit_Details_Field.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        UserEdit_Details_Field.setLineWrap(true);
        UserEdit_Details_Field.setRows(5);
        UserEdit_Details_Field.setTabSize(1);
        UserEdit_Details_Field.setToolTipText("Enter details about the item.");
        UserEdit_Details_Field.setWrapStyleWord(true);
        UserEdit_Details_Container.setViewportView(UserEdit_Details_Field);

        UserEdit_Category_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserEdit_Category_Label.setText("Category:");
        UserEdit_Category_Label.setToolTipText("");

        UserEdit_Category_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        UserEdit_Price_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserEdit_Price_Label.setText("Price:");

        UserEdit_Price_Field.setToolTipText("Enter the item's price.");

        UserEdit_Update_Button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserEdit_Update_Button.setText("Update Advertisement");
        UserEdit_Update_Button.setToolTipText("Save changes to the advertisement.");
        UserEdit_Update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserEdit_Update_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UserEdit_Update_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UserEdit_Category_Label)
                            .addComponent(UserEdit_Details_Label)
                            .addComponent(UserEdit_Price_Label)
                            .addComponent(UserEdit_Title_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserEdit_Price_Field)
                            .addComponent(UserEdit_Title_Field)
                            .addComponent(UserEdit_Details_Container)
                            .addComponent(UserEdit_Category_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserEdit_Title_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserEdit_Title_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserEdit_Details_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserEdit_Details_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserEdit_Category_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserEdit_Category_Label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserEdit_Price_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserEdit_Price_Label))
                .addGap(18, 18, 18)
                .addComponent(UserEdit_Update_Button)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserEdit_Update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserEdit_Update_ButtonActionPerformed
        advertisement.setID(this.adID);
        advertisement.setTitle(this.UserEdit_Title_Field.getText().trim());
        advertisement.setDetails(this.UserEdit_Details_Field.getText().trim());
        Record category = (Record) this.UserEdit_Category_ComboBox.getSelectedItem();
        advertisement.setCategoryID(category.getID());
        try {
            if (StringUtils.isNullOrEmpty(this.UserEdit_Price_Field.getText())) {
                JOptionPane.showMessageDialog(this, "Price field is empty", "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                advertisement.setPrice(Float.parseFloat(this.UserEdit_Price_Field.getText()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Price field is not a number", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (advertisement.getTitle().equals("")) {
            JOptionPane.showMessageDialog(this, "Title field is empty", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (advertisement.getDetails().equals("")) {
            JOptionPane.showMessageDialog(this, "Details field is empty", "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        boolean result = DB.userUpdateAdvertisement(advertisement);
        if (result) {
            JOptionPane.showMessageDialog(this,
                    "The advertisement was updated",
                    "Confirmation",
                    JOptionPane.INFORMATION_MESSAGE);
            parent.populateUserAdsTable(userID);
            this.setVisible(false);
        }
    }

    private void populateTable(int adID) {
        advertisement = DB.getAdByID(adID);
        this.UserEdit_Title_Field.setText(advertisement.getTitle());
        this.UserEdit_Details_Field.setText(advertisement.getDetails());
        this.UserEdit_Price_Field.setText(String.valueOf(advertisement.getPrice()));
        try {
            this.UserEdit_Category_ComboBox.setSelectedItem(Utilities.findCategory(this.UserEdit_Category_ComboBox, advertisement.getCategoryID()));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void populateCategories() {
        this.UserEdit_Category_ComboBox.removeAllItems();
        for (Record category : DB.getCategories()) {
            this.UserEdit_Category_ComboBox.addItem(category);
        }
    }//GEN-LAST:event_UserEdit_Update_ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Record> UserEdit_Category_ComboBox;
    private javax.swing.JLabel UserEdit_Category_Label;
    private javax.swing.JScrollPane UserEdit_Details_Container;
    private javax.swing.JTextArea UserEdit_Details_Field;
    private javax.swing.JLabel UserEdit_Details_Label;
    private javax.swing.JTextField UserEdit_Price_Field;
    private javax.swing.JLabel UserEdit_Price_Label;
    private javax.swing.JTextField UserEdit_Title_Field;
    private javax.swing.JLabel UserEdit_Title_Label;
    private javax.swing.JButton UserEdit_Update_Button;
    // End of variables declaration//GEN-END:variables
}
